job-build:
  tags:
    - ci utest
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=OFF
    - make -j
    - cmake .. -DBUILD_TEST=ON
    - make -j
    - ./test/dev/dev_utest
    - ./test/net/net_utest
    - ./test/protocol/protocol_utest
    - ./test/module/module_utest